# Stable reason codes for deterministic verification outputs.
# Keep these strings stable once published.

# Zip / input safety
ERR_BAD_ZIP = "ERR_BAD_ZIP"
ERR_BAD_PATH = "ERR_BAD_PATH"
ERR_PATH_TRAVERSAL = "ERR_PATH_TRAVERSAL"
ERR_SYMLINK = "ERR_SYMLINK"
ERR_FILE_COUNT_LIMIT = "ERR_FILE_COUNT_LIMIT"
ERR_SIZE_LIMIT = "ERR_SIZE_LIMIT"
ERR_SINGLE_FILE_SIZE_LIMIT = "ERR_SINGLE_FILE_SIZE_LIMIT"

# Integrity / evidence
ERR_HASH_MISMATCH = "ERR_HASH_MISMATCH"
ERR_CHAIN_BREAK = "ERR_CHAIN_BREAK"
ERR_MANIFEST_MISSING = "ERR_MANIFEST_MISSING"
ERR_WINDOW_SEAL_BROKEN = "ERR_WINDOW_SEAL_BROKEN"

# DriftLock (v1_4)
ERR_DRIFT_MANIFEST_WINDOWS_MISSING = "ERR_DRIFT_MANIFEST_WINDOWS_MISSING"
ERR_DRIFT_DUPLICATE_WINDOW_ID = "ERR_DRIFT_DUPLICATE_WINDOW_ID"
ERR_DRIFT_WINDOW_MISSING_IN_ZIP = "ERR_DRIFT_WINDOW_MISSING_IN_ZIP"
ERR_DRIFT_EXTRA_WINDOW_IN_ZIP = "ERR_DRIFT_EXTRA_WINDOW_IN_ZIP"
ERR_DRIFT_WINDOW_ORDER = "ERR_DRIFT_WINDOW_ORDER"
ERR_DRIFT_SEALED_READ_ERROR = "ERR_DRIFT_SEALED_READ_ERROR"

# Generic / unexpected
ERR_ZIPGUARD_UNAVAILABLE = "ERR_ZIPGUARD_UNAVAILABLE"
ERR_ZIP_GUARD_EXCEPTION = "ERR_ZIP_GUARD_EXCEPTION"
ERR_DETECTIVE_VERIFY_FAILED = "ERR_DETECTIVE_VERIFY_FAILED"
ERR_INVALID_JSON_OUTPUT = "ERR_INVALID_JSON_OUTPUT"
ERR_REPORT_SCHEMA_INVALID = "ERR_REPORT_SCHEMA_INVALID"
ERR_INTERNAL = "ERR_INTERNAL"
